# Generated by Django 5.0.6 on 2024-11-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time_zone',
            field=models.CharField(default='America/Los_Angeles', max_length=100),
        ),
    ]
