# Generated by Django 5.0.6 on 2024-12-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_address_alter_event_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
    ]
