# Generated by Django 5.0.6 on 2025-01-01 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='event_start_date_time',
        ),
        migrations.AddField(
            model_name='event',
            name='event_end_date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
