import type { Metadata } from 'next';
// import { Inter } from "next/font/google";
import './globals.css';
import Header from '../app/components/layouts/header/Header';
import Footer from '../app/components/layouts/footer/Footer';
import Providers from '../providers/Providers';
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <Header />
                    <main>{children}</main>
                    <Footer />
                </Providers>
            </body>
        </html>
    );
}
