# Generated by Django 5.0.6 on 2024-05-29 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.DateField(default=datetime.date.today)),
                ('introduction', models.CharField(max_length=500)),
                ('created', models.DateField(default=datetime.date.today)),
                ('updated', models.DateField(blank=True)),
            ],
        ),
    ]
